### ISSUE TITLE
Phpspy on Apache2 PHP in Docker

### ISSUE THREAD

**Issue by AlexeyPlodenko** [adsr/phpspy#118]
I am trying to use Phpspy in a Docker instance that is created that way:

```dockerfile
FROM php:7.3-apache
...
```

I have restricted the amount of Apache instances running by configuring MPM to have only 1 server running:

```
<IfModule mpm_prefork_module>
        StartServers 1
        MinSpareServers 1
        MaxSpareServers 1
        MaxRequestWorkers 1
        MaxConnectionsPerChild   0
</IfModule>
```

After executing the `top` command:

```
# top
top - 13:45:21 up 3 days, 34 min,  0 users,  load average: 0.20, 0.09, 0.14
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni, 99.2 id,  0.0 wa,  0.0 hi,  0.8 si,  0.0 st
MiB Mem :  19162.5 total,   7959.1 free,   1459.7 used,   9743.7 buff/cache
MiB Swap:   5120.0 total,   5120.0 free,      0.0 used.  16983.6 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0  171620  34292  25680 S   0.0   0.2   0:00.10 apache2
   17 www-data  20   0  186768  33436   9608 S   0.0   0.2   0:05.06 apache2
   18 root      20   0    2416    572    504 S   0.0   0.0   0:00.02 sh
  145 root      20   0    6992   3280   2720 R   0.0   0.0   0:00.00 top
```

We can see there only `apache2` instances running with PID 1 and PID 17.

When I try to phpspy the PID 1, I am getting an error:

```
copy_proc_mem: Failed to copy executor_globals; err=Operation not permitted raddr=0x7fe49effdd80 size=496
copy_proc_mem: Failed to copy executor_globals; err=Operation not permitted raddr=0x7fe49effdd80 size=496
copy_proc_mem: Failed to copy executor_globals; err=Operation not permitted raddr=0x7fe49effdd80 size=496
....
```

Trying to phpspy the PID 17, also an error:

```
# phpspy -p 17
awk: cannot open /proc/17/maps (Permission denied)
popen_read_line: No stdout; cmd=awk '/libphp[78]/{print $NF; exit 0} END{exit 1}' /proc/17/maps || readlink /proc/17/exe
get_php_bin_path: Failed
```

Please advice, if I am doing something wrong.

**Comment by Jongy** [comment]
phpspy requires elevated privileges that are not normally given to a Docker container. You need to start it with `--privileged` in your `docker run` commandline (or, alternative, disable seccomp for the container & give it `CAP_SYS_PTRACE`, IIRC those 2 should be enough)

Another option is to run phpspy outside of the container - it can happily profile containerized processes.

**Comment by adsr** [comment]
Feel free to reopen if you're still having trouble.

**Comment by zeleniy** [comment]
It would be nice to write about this problem on main page in troubleshooting section and provide examples for `docker run` and `docker compose`.
```
services:
  php:
    image: php:7.1-fpm-alpine
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
  ...
```
Or try to use  `--cap-add` flag: `docker run --cap-add=SYS_PTRACE...`. See «[Why strace doesn't work in Docker](https://jvns.ca/blog/2020/04/29/why-strace-doesnt-work-in-docker/)» for details.

Also you need to install some packages on Alpine Linux:
```
apk add make build-base perl
```
