### ISSUE TITLE
Build Stuff

### ISSUE THREAD

**Issue by krakjoe** [adsr/phpspy#13]
1) Very cool ...
  2) What do you think about adopting cmake/autotools ?
  3) I've got a sort of fuzzy idea to use php-config to extract struct layout from headers in a given build environment, any thoughts on that ?

**Comment by adsr** [comment]
Hey, thanks for checking it out.

> What do you think about adopting cmake/autotools ?

Not opposed to merging cmake and autotools configs esp if we can preserve the simple makefile route (my pref).

> I've got a sort of fuzzy idea to use php-config to extract struct layout from headers in a given build environment, any thoughts on that ?

Do you mean statically analyzing header files to generate the structs? That would be rad. Issue #10 is tangentially related.

**Comment by krakjoe** [comment]
Closed by #61
