### ISSUE TITLE
copy_proc_mem: Failed to copy executor_globals; err=Function not implemented

### ISSUE THREAD

**Issue by oleg-filiutsich** [adsr/phpspy#137]
I try use phpspy latest version in k8s php-fpm pod with already configured SYS_PTRACE.
But got error
```
# ./phpspy -P php
copy_proc_mem: Failed to copy executor_globals; err=Function not implemented raddr=0x55a568a21300 size=1776
```

**Comment by adsr** [comment]
Some amount of these errors is normal. Is it getting any stacktraces at all or all errors?

You may want to try again with the latest version if you haven't already. A bugfix for 8.3 was added in https://github.com/adsr/phpspy/commit/602ad763fb034bb68a0db4190bae8b6c6da7461d.

**Comment by adsr** [comment]
Feel free to reopen
