### ISSUE TITLE
SUPPORT DOCKER

### ISSUE THREAD

**Issue by khalid-sanggoyod** [adsr/phpspy#139]
Is it okay to compile the PHPspy on our docker if ever we don't want to install Linux OS? Thanks

**Comment by adsr** [comment]
Echoing what I wrote [here](https://github.com/adsr/phpspy/issues/138#issuecomment-2053767834) you can of course try to compile it inside colima or Docker Desktop, but you'd still be limited to profiling PHP scripts inside that environment, so I don't think it'd be that useful.

phpspy relies on Linux-specific syscalls and assumes PHP is an ELF executable. We'd need to change those guts for mac compat. Issue https://github.com/adsr/phpspy/issues/50 tracks that. As I mentioned there, I'm not a mac user and don't have an environment to develop this feature. If I can get my hands on an old mac or if someone can provide a remote shell, I'd be happy to take a shot implementing it.
