### ISSUE TITLE
APACHE SERVER NOT WORKING

### ISSUE THREAD

**Issue by khalid-sanggoyod** [adsr/phpspy#142]
Do you have an idea why all PIDs of the Apache server are not working to this command `./phpspy -p $(pgrep -n httpd)`?

![image](https://github.com/adsr/phpspy/assets/48314544/793c74a3-63f2-489f-b665-82ed85c88b92)

**Comment by adsr** [comment]
Hi, are there any errors you see? Given the screenshot I'd guess you'd want `./phpspy -p $(pgrep -nx apache2)`

**Comment by adsr** [comment]
Feel free to reopen
