### ISSUE TITLE
add ability to print any `$_VAR` super global

### ISSUE THREAD

**Issue by mackenziestarr** [adsr/phpspy#21]
now that we find the `php_core_globals` address and can print a basic representation of zend_array with `print_array_recursive` — we can easily grab any of the following info

https://github.com/php/php-src/blob/029a8c9882c70bf1326f8bf1b9446bc11867a80c/main/php_globals.h#L39-L45
```
#define TRACK_VARS_POST		0
#define TRACK_VARS_GET		1
#define TRACK_VARS_COOKIE	2
#define TRACK_VARS_SERVER	3
#define TRACK_VARS_ENV		4
#define TRACK_VARS_FILES	5
#define TRACK_VARS_REQUEST	6
```

**Comment by adsr** [comment]
Proposed invocation:

    --peek-global=<global>.<key>

Proposed output:

    # globalpeek <global>.<key> = <value>

We can dump these at the end of each stacktrace along with `--request-info` and memory (#44) bits.

For reference, varpeek invocation is `--peek-var=<varname>@<path>:<lineno>` yielding `# varpeek <varname>@<path>:<lineno> = <value>` output.

**Comment by adsr** [comment]
8eced0c4da4145708f3367dd1677c435f77db602 added this feature

**Comment by mackenziestarr** [comment]
Nice!
