### ISSUE TITLE
Document termbox dependency

### ISSUE THREAD

**Issue by nickpeirson** [adsr/phpspy#22]
Commit df75b6ffdf2600e2f81a2f616f6036c41ec6bb7e added a dependency on termbox which means following the simple make instructions in the readme now blows up:
```
$ make
cc -Wall -Wextra -pedantic -g -Ofast -pthread  -I.  -DUSE_READELF=1 phpspy.c pgrep.c top.c addr_libdw.c addr_readelf.c -o phpspy
In file included from phpspy.c:1:0:
phpspy.h:24:21: fatal error: termbox.h: No such file or directory
 #include <termbox.h>
                     ^
compilation terminated.
In file included from pgrep.c:1:0:
phpspy.h:24:21: fatal error: termbox.h: No such file or directory
 #include <termbox.h>
                     ^
compilation terminated.
In file included from top.c:1:0:
phpspy.h:24:21: fatal error: termbox.h: No such file or directory
 #include <termbox.h>
                     ^
compilation terminated.
In file included from addr_libdw.c:1:0:
phpspy.h:24:21: fatal error: termbox.h: No such file or directory
 #include <termbox.h>
                     ^
compilation terminated.
In file included from addr_readelf.c:1:0:
phpspy.h:24:21: fatal error: termbox.h: No such file or directory
 #include <termbox.h>
                     ^
compilation terminated.
make: *** [phpspy] Error 1
```

Installing https://github.com/nsf/termbox allows make to complete successfully (albeit with a lot of warnings), but this could probably do with documenting.

Great tool by the way! I've already used it in anger a couple of times to work out what a stuck process was doing.

**Comment by adsr** [comment]
Thanks for the report and glad to hear you find it useful. fc58c9b should fix the build. termbox is supposed to be optional. Re: warnings, assuming you're on an older version of gcc, you can build like `CFLAGS='-std=c99' make`. I'd like to make it c90 clean in the future. Thanks again!

**Comment by nickpeirson** [comment]
Yup, that fixed it. Quick work, thanks!
