### ISSUE TITLE
get_php_bin_path failing to find path to PHP binary

### ISSUE THREAD

**Issue by nickpeirson** [adsr/phpspy#24]
I'm running phpspy on one system where it fails to find the PHP path. It blows up with the error:
```
popen_read_line: No stdout; cmd=grep ' 0$' /proc/5694/maps | head -n1
get_php_base_addr: Failed to get start_addr
```

Tracking this back it's because `get_php_bin_path` returns `0`.

Looking at `/proc/5694/maps` shows that the first line doesn't contain the path to the PHP binary, so `awk 'NR==1{path=$NF} /libphp7/{path=$NF} END{print path}' /proc/%d/maps` fails to find it.

I've attached the [memory map for the process](https://github.com/adsr/phpspy/files/2454249/procmap.txt). I couldn't come up with a way to find the path reliably or I would've submitted a PR, but hopefully you can. If not, I wondered if it would make sense to allow specifying the path via a command line option? As a quick hack I've temporarily hardcoded the path.

If you do go down the route of adding a command line option I think it would be worth changing the error message to make it clear what the issue is, as currently it takes a bit of digging to get from `get_php_base_addr: Failed to get start_addr` to working out it can't find the binary. It would be straightforward enough to add a check in `get_php_bin_path` to see if `path` did exist.

**Comment by adsr** [comment]
Thanks for the report. Can you try with the libdw version? We'd like to remove the readelf method once we move libdw into the repo as a submodule or a vendor lib. libdw/libdwfl[0] is not packaged as consistently as readelf which is the main reason why readelf is the default.

[0] https://sourceware.org/git/?p=elfutils.git;a=tree;f=libdwfl;h=547d55f22ca1eb07f93b6888292af53f317c465b;hb=HEAD

**Comment by nickpeirson** [comment]
The version compiled with `libdw` worked perfectly, thanks. I'll stick to using these builds going forward 👍
