### ISSUE TITLE
Find segfault in libdw address finder

### ISSUE THREAD

**Issue by adsr** [adsr/phpspy#27]
Able to reproduce consistently with `sudo ./phpspy -V73 -r qcup -P '-x php'` and then running `make test` in the php-src repo, which spawns a lot of php procs.

Unsure if the problem is in phpspy code or somewhere in libdw. I've seen it manifest in a few ways:

- Bad pointer returned from [dwfl_module_getsym_info][0] + segfault on next `strcmp`
- NULL [dwarf_lookup_symbol][1] + segfault on next `strcmp`
- Stack corruption

Could all be the same underlying problem.

[0]: https://github.com/adsr/phpspy/blob/bb1cb479da51b7bfda10762ee15f1faa5d218575/addr_libdw.c#L79
[1]: https://github.com/adsr/phpspy/blob/bb1cb479da51b7bfda10762ee15f1faa5d218575/addr_libdw.c#L89

**Comment by mackenziestarr** [comment]
I think this partially has to do with threading done in pgrep mode and the fact that [`dwarf_lookup_symbol`](https://github.com/adsr/phpspy/blob/bb1cb479da51b7bfda10762ee15f1faa5d218575/addr_libdw.c#L13) is global. We should patch it by passing the symbol we are searching for into the callback like we currently do with [`raddr`](https://github.com/adsr/phpspy/blob/bb1cb479da51b7bfda10762ee15f1faa5d218575/addr_libdw.c#L73)
