### ISSUE TITLE
test breaks on php 7.2

### ISSUE THREAD

**Issue by mackenziestarr** [adsr/phpspy#30]
nice work on setting up a test, I noticed that it fails on PHP 7.2 here https://github.com/adsr/phpspy/blob/5f133757ccc9ba9764c5b0b2313907018475bfae/tests/test_simple.sh#L11

the equivalent trace on PHP 7.2 looks like this:
```
0 usleep <internal>:-1
1 <main> <internal>:-1
# uri = -
# path = -
# qstring = -
# cookie = -
# ts = 1540393892.910322
```

**Comment by adsr** [comment]
Nice catch, b4ed61b should fix.
