### ISSUE TITLE
Add more output format options

### ISSUE THREAD

**Issue by mlauter** [adsr/phpspy#4]
It would be useful to have support for various output formats along with the raw data (e.g. [Callgrind](http://kcachegrind.sourceforge.net/html/CallgrindFormat.html) and summary stats.) Flamegraph formatted output could be incorporated into the profiler as another output format option.

Users could then pass a `-f` option to specify the type of output.

Another option would be to have separate scripts like `stackcollapse-phpspy` that would transform the raw stacks into various other formats post hoc.

**Comment by adsr** [comment]
Callgrind output is supported since 4241ad4bffb76089a23751d5ffcbc37f51bff3b1
