### ISSUE TITLE
Docker: Failed to copy executor_globals; Operation not permitted raddr

### ISSUE THREAD

**Issue by rlalak** [adsr/phpspy#54]
When I try to use phpspy inside docker container I got error:
```
copy_proc_mem: Failed to copy executor_globals; err=Operation not permitted raddr=0x7f30b3b0e240 size=496
```

Step to reporduce:
```
docker run -p 8181:80 -d --name=apache php:apache
docker exec  -it apache bash
```
inside container:
```
#add index file
echo "<?php phpinfo();" > index.php

# install requried libs
apt-get update
apt-get install git python gcc

cd ..
git clone https://github.com/adsr/phpspy.git
cd phpspy/
make
./phpspy -p 1
```
I tried on other images (centos+fpm) and I have the same error.

**Comment by adsr** [comment]
Hello @rlalak. It's likely you need to grant `SYS_PTRACE` to the container which is required by `process_vm_readv` which phpspy relies on. Try `docker run --cap-add SYS_PTRACE ...`. Feel free to reopen if that doesn't work. Thanks.

**Comment by rlalak** [comment]
@adsr thanks a lot, it wokrs :)
