### ISSUE TITLE
Support --time-limit=XXX  option which limit tracing by time in ms instead of --limit which mean "count of traces"

### ISSUE THREAD

**Issue by Slach** [adsr/phpspy#56]
this options will be very usefull when run phpspy in non interactive mode
currenly we can try calculate expected --limit value option as 
```--limit = (planing rps * count --pgrep processes * --rate-hz)```

but planning rps have high volatility and use --time-limit=60000 (60 seconds) should impove usability usage of phpspy

**Comment by adsr** [comment]
Feature added in e9927c8e7a8cdf6763d163bfaa60cec313cb37c0. Thanks!
