### ISSUE TITLE
Fix `--limit` and `--time-limit-ms` in `--pgrep` mode

### ISSUE THREAD

**Issue by adsr** [adsr/phpspy#58]
Currently `--limit` only works in single-pid mode. In pgrep mode, once a limit is reached the worker does exit but a new worker is spawned in its place.

**Comment by Slach** [comment]
current workaround for problem described here https://github.com/adsr/phpspy/issues/42
```bash
pgrep php-fpm | xargs -P0 -I{} bash -c '/opt/phpspy/phpspy -p {} -V73 --time-limit-ms 60000 | /opt/phpspy/stackcollapse-phpspy.pl | /opt/phpspy/vendor/flamegraph.pl > /tmp/phpspy-flamegraph.{}.svg'
```
