### ISSUE TITLE
USE_ZEND

### ISSUE THREAD

**Issue by krakjoe** [adsr/phpspy#62]
I don't think this can work: phpspy seems to reference private structs like zend_alloc_globals ... which are misnamed as they aren't global :)

Propose that this option is dropped from the build: It's possible to get some of the headers from the build environment (which I would suppose most people don't have installed), but phpspy must still define those private structs. In addition the ability of a single binary to interact with many versions is quite valuable, and you would loose that in a USE_ZEND build. Lastly, anything that makes the source more easily understandable is a win.

**Comment by adsr** [comment]
Fixed USE_ZEND builds in 7ca9cfd8296e6a0477f6b0eeb93af42362588561. Punting on this for now.
