### ISSUE TITLE
Unable to build on FreeBSD

### ISSUE THREAD

**Issue by tuaris** [adsr/phpspy#70]
Trying to build on FreeBSD 12.0-RELEASE using the provided instructions results in:

```
make: "/usr/home/Development/phpspy/Makefile" line 22: Need an operator
make: "/usr/home/Development/phpspy/Makefile" line 24: Need an operator
make: "/usr/home/Development/phpspy/Makefile" line 25: Missing dependency operator
make: "/usr/home/Development/phpspy/Makefile" line 28: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/Development/phpspy
```

**Comment by adsr** [comment]
Hi @tuaris. phpspy only supports Linux at the moment as it currently relies on a Linux-only system call, `process_vm_readv`. If you'd like to take a shot at porting it, using `gmake` might unblock you at this point. Thanks.
