### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by jgmdev** [adsr/phpspy#72]
I created a [packaging script for archlinux](https://aur.archlinux.org/packages/phpspy/) on the AUR  for easier installation and the package should include license information, didn't found any license file on the repo so was wondering what license will this project be licensed as :)

For the moment I just added the 'unknown' license placeholder. Thanks for sharing such a nice application!

**Comment by adsr** [comment]
Added in 6a1c47594ab8d7286f6ce22f8d82be50dcaebb74. Thank you for the reminder.
