### ISSUE TITLE
Production readyness

### ISSUE THREAD

**Issue by qcho** [adsr/phpspy#80]
Hello,

I'm planning to use phpspy in production and since it needs root access to do it's magic I would like to know how production-safe/ready you think this project is.
Also if there are any security audit's on the source to make my life easier.

My intentions are:
1) peek php processes from time to time.
2) keep it running all the time gathering profile-sampling information of production environments.

Im sure usecase 1. is ok.
On the 2nd usecase, xhprof is not compatible with php7, one can use tideways's fork. But tideways removed the sampling module in the portability effort.

So is it safe to be running constantly? Is that considered a common usecase?
Are there any known issues or missing things to take into consideration.

**Comment by adsr** [comment]
Hi @qcho. There have not been any security audits of the code to my knowledge. It resolves memory addresses in target processes by reading procfs and calling objdump. I've filed ticket #81 to shell-escape the parameters in that code. That is one vuln I can think of that applies if you are running phpspy against untrusted binaries or on a shared host.

Performance-wise, it is safe to run constantly in my experience. It does not allocate any heap after startup (unless using callgrind mode or top mode). It does not do any network. It does not write to disk unless you instruct it to. If you end up using it, I encourage you to report any issues you might find.

Thanks!

**Comment by qcho** [comment]
I appreciate the quick answer. Thanks! I'll report anything useful ^_^
