### ISSUE TITLE
Interlaced output from multiple threads being traced

### ISSUE THREAD

**Issue by parthpatel1001** [adsr/phpspy#83]
Occasionally `phpspy` will interlace output from multiple threads of tracing like so:

```
ternal>:-1
1 FooBarBaz::execute /var/foo/bar/phplib/Baz/DBBaz.php:104
2 FooBarBaz::bindAndExecuteStatement /var/foo/bar/Baz/Baz/Baz.php:1379
3 FooBarBaz::callFunc /var/foo/bar0 curl_exec <internal>:-1
1 Baz::execute /var/foo/bar/Bazify.php:152
2 FooBarBaz::singleCurlFetch /var/foo/bar/Baz/SuperBaz.php:503
```

An `strace` points to [these fprintf calls](https://github.com/adsr/phpspy/blob/master/event_fout.c#L116) happening multiple times on a single trace/with multiple threads they could be overlapping with each other.

@keyurdg suggested: 

> Instead of line buffering [here](https://github.com/adsr/phpspy/blob/4241ad4bffb76089a23751d5ffcbc37f51bff3b1/event_fout.c#L144) maybe full buffer `_IOFBF` and `fflush` when completed 

> and fflush [here](https://github.com/adsr/phpspy/blob/4241ad4bffb76089a23751d5ffcbc37f51bff3b1/event_fout.c#L114)

**Comment by adsr** [comment]
Thanks!
