### ISSUE TITLE
Add trace collection info as an option

### ISSUE THREAD

**Issue by parthpatel1001** [adsr/phpspy#88]
It would be nice to get info around the trace that was collected like which pid was used and the time the trace was pulled:
```
# ts = 1572757654.468000
# collected_at = 1572757654.510204
# pid = 26089
```

**Comment by parthpatel1001** [comment]
Added this in a PR here https://github.com/adsr/phpspy/pull/89

**Comment by adsr** [comment]
Added in 58120721e6411a28266d5829c102517f6aa71fe3
