### ISSUE TITLE
Add an option to raise the maximum size of event_handler_fout_udata_s.buf?

### ISSUE THREAD

**Issue by TysonAndre** [adsr/phpspy#94]
Alternately, cut the stack frames off at the first frame that would cause the size to exceed 4096 bytes.

In deeply nested method calls (e.g. 45 lines with an average of 100 columns per line), the total size of the text of the stack trace can exceed 4096 bytes.

Currently, phpspy refuses to print the stack trace, and the end result is inaccurate due to omitting those traces. (due to how the `try` macro is used for `try(rv, context->event_handler(context, PHPSPY_TRACE_EVENT_FRAME));` - the entire function exits without printing to `stdout` instead of just skipping the remaining frames

**Comment by adsr** [comment]
Added in 5fee40c and 9ec7d49. Thanks for the feature suggestion @TysonAndre.
