### ISSUE TITLE
Errors being written to stdout

### ISSUE THREAD

**Issue by ttk** [adsr/phpspy#99]
Seems like this commit 3b9df5667d6774a430bf006a264a0b9b865b4331 introduced a problem causing stderr being written to stdout.   After checking out the prior commit, that problem goes away.

**Comment by adsr** [comment]
@ttk Thank you for the report. It is pretty magical so I am not surprised it breaks. However, strangely, I cannot repro it on my setup. Can you `strace -f -s256 -o/tmp/strace phpspy ...` and share `/tmp/strace`? Feel free to email it instead if you don't want to share publicly. Thanks.

**Comment by adsr** [comment]
@ttk Let me know if 90eb31c works as expected. Thank you.

**Comment by ttk** [comment]
Yes, that worked!  Thanks!
